language: node_js
os: linux
node_js:
  - "8"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install codecov -g
  - npm install coveralls -g
  - npm install codeclimate-test-reporter -g
  - npm install
script:
  - npm test
after_success:
  - codecov
  - coveralls < ./coverage/lcov.info
  - CODECLIMATE_REPO_TOKEN=0d59acc244be097b9b3eaefad86d6b958e88a81b0d0a6acc987eced0204ff7c6 codeclimate-test-reporter < ./coverage/lcov.info
